export const FETCH_CHART = 'FETCH_CHART';
export const FETCH_CHART_SUCCESS = 'FETCH_CHART_SUCCESS';
export const FETCH_CHART_FAILS = 'FETCH_CHART_FAILS';

export const CREATE_CHART = 'CREATE_CHART';
export const CREATE_CHART_SUCCESS = 'CREATE_CHART_SUCCESS';
export const CREATE_CHART_FAILS = 'CREATE_CHART_FAILS';

export const FETCH_SUMMARY = 'FETCH_SUMMARY';
export const FETCH_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUCCESS';
export const FETCH_SUMMARY_FAILS = 'FETCH_SUMMARY_FAILS';

export const CREATE_SUMMARY = 'CREATE_SUMMARY';
export const CREATE_SUMMARY_SUCCESS = 'CREATE_SUMMARY_SUCCESS';
export const CREATE_SUMMARY_FAILS = 'CREATE_SUMMARY_FAILS';